---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routines-microservice-stable
  labels:
    app.kubernetes.io/name: routines-microservice-stable
    app.kubernetes.io/part-of: application-layer
    app.kubernetes.io/component: backend-application
    app.kubernetes.io/version: 1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: routines-microservice-stable
  template:
    metadata:
      labels:
        app.kubernetes.io/name: routines-microservice-stable
        app.kubernetes.io/part-of: application-layer
        app.kubernetes.io/component: backend-application
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - name: routines-microservice
          image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/routines-microservice:$ECR_TAG
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: '80'

            - name: NATS_CONNECTION_STRING
              value: nats://nats.nats.svc.cluster.local:4222

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: routines-microservice
                  key: database-url

            - name: AUTHZ_ISSUER
              value: https://auth.getbud.co/

            - name: RABBITMQ_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: routines-microservice
                  key: rabbitmq-connection-string

      initContainers:
        - name: routines-microservice-stable-execute-migrations
          image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/routines-microservice:$ECR_TAG
          command: ['npm', 'run', 'migrate:prod']
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: routines-microservice
                  key: database-url

        - name: routines-microservice-stable-add-missing-teams-configurations
          image: 904333181156.dkr.ecr.sa-east-1.amazonaws.com/routines-microservice:$ECR_TAG
          command: ['npm', 'run', 'global:settings:prod']
          env:
            - name: NATS_CONNECTION_STRING
              value: nats://nats.nats.svc.cluster.local:4222
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: routines-microservice
                  key: database-url

            - name: RABBITMQ_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: routines-microservice
                  key: rabbitmq-connection-string
