version: "3"

services:
  postgres:
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - ./postgres-data/:/data/postgres
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - bud-routines

  routine-microservice:
    build: .
    ports:
      - 3002:3000
    networks:
      - bud-rabbitmq
      - bud-routines
    links:
      - postgres
    environment:
      PORT: 3000
      NATS_CONNECTION_STRING: nats://broker-nats:4222
      DATABASE_URL: postgresql://routines:changeme@postgres:5432/routines?schema=public
      AUTHZ_ISSUER: 'https://dev-0qjqjqjq.auth0.com/'
      RABBITMQ_CONNECTION_STRING: amqp://rabbitmq:5672

networks:
  bud-rabbitmq:
    external: true
  bud-routines: